#!/bin/bash
# build tool

if [ "$1" == "x64" ]; then
	if [ "$2" == "Debug" ]; then
		shift 2;
		make -C bzlib MINGW=x86_64-w64-mingw32- DEBUG=1 $*;
		make MINGW=x86_64-w64-mingw32- DEBUG=1 $*;
	else
		shift 2;
		make -C bzlib MINGW=x86_64-w64-mingw32- DEBUG=0 $*;
		make MINGW=x86_64-w64-mingw32- $*;
	fi
else
	if [ "$2" == "Debug" ]; then
		shift 2;
		make -C bzlib DEBUG=1 $*;
		make DEBUG=1 $*;
	else
		shift 2;
		make -C bzlib DEBUG=0 $*
		make $*;
	fi
fi

